### ISSUE TITLE
In __init__ file ttyl is written two times

### ISSUE THREAD

**Issue by prashant2-4-4** [aman2656/text2emotion-library#5]
In __init__ file ttyl is written two times inside the shortcuts sections.

![ttyl name](https://user-images.githubusercontent.com/55931362/123838853-12ab4480-d92a-11eb-95d4-eff4dfde1a89.jpeg)
. 
You can see this in the screenshot attached.

**Comment by prashant2-4-4** [comment]
@aman2656  I want to work on this please assign this to me.

**Comment by prashant2-4-4** [comment]
@ShivamSharma26

**Comment by Amey23** [comment]
> @aman2656 I want to work on this please assign this to me.



> In **init** file ttyl is written two times inside the shortcuts sections.
> 
> ![ttyl name](https://user-images.githubusercontent.com/55931362/123838853-12ab4480-d92a-11eb-95d4-eff4dfde1a89.jpeg)
> .
> You can see this in the screenshot attached.

Thank you for finding out the mistake, we will work on it.
